### ISSUE TITLE
Feature request: control max fps

### ISSUE THREAD

**Issue by Phuker** [ImBaedin/Thpace#2]
This project is awesome : )
i'd like to limit the FPS to save energy, can you add something like `maxFPS` to the settings?
Thank You!
P.S. here is my ugly patch (I know few about JavaScript, i'm sure you have better code):

```JavaScript
{
      key: "animate",
      value: function animate() {
        window.xxxx = window.xxxx || 0;
        var __now = Date.now();
        var __elapsed = __now - window.xxxx;
        if (__elapsed > (1000 / 10)){
            window.xxxx = __now;
            /// some animation code
        }
        requestAnimationFrame(this.animate.bind(this));
      }
}
```

**Comment by ImBaedin** [comment]
I will begin looking into it tomorrow!

**Comment by ImBaedin** [comment]
I looked into when I said I would, and realized that the code was all bad. I'm currently doing a complete rewrite, probably about ~70% done. The new version seems to be maintaining a cool 60fps on my laptop without a hitch, as well as supporting updating most settings in real time.

Oh and with a maxFps setting :D
